# Generated by Django 2.2 on 2019-04-21 15:51

import Image_Style_Transfer_AI.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(upload_to=Image_Style_Transfer_AI.models.get_upload_path)),
                ('image_two', models.ImageField(upload_to=Image_Style_Transfer_AI.models.get_upload_path)),
                ('image_output', models.ImageField(upload_to=Image_Style_Transfer_AI.models.get_upload_path)),
                ('artist', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Image_Style_Transfer_AI.User')),
            ],
        ),
    ]
