# Generated by Django 2.2 on 2019-04-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Style_Transfer_AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
