# Generated by Django 2.2 on 2019-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Image_Style_Transfer_AI', '0002_auto_20190421_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=250),
        ),
    ]
